default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_general_ci # 照合順序を日本語対応に
  charset: utf8mb4              # 文字セットを明示的に指定
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch("MYSQL_DB") { '' } %> # .env 環境変数を参照
  username: <%= ENV.fetch("MYSQL_USER") { '' } %> # .env 環境変数を参照
  password: <%= ENV.fetch("MYSQL_ROOT_PASSWORD") { '' } %> # .env 環境変数を参照
  host: db # docker-compose.yml の DB のサービス名を指定

development:
  <<: *default
  database: <%= ENV.fetch("MYSQL_DB") { '' } %>_development # .env 環境変数を参照

test:
  <<: *default
  database: <%= ENV.fetch("MYSQL_DB") { '' } %>_test # .env 環境変数を参照

production:
  <<: *default
  database: app_production
  username: app
  password: <%= ENV["APP_DATABASE_PASSWORD"] %>
